# Generated by Django 2.1.4 on 2019-01-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_auto_20190126_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
