# Generated by Django 2.1.4 on 2019-01-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_auto_20190126_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='name',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='keyword',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
