# Generated by Django 2.1.4 on 2019-01-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_auto_20190126_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='keyword',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
